import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Heart, Users, Building2, Clock } from "lucide-react";
import { Button } from "./ui/button";
import { Link } from "react-router-dom";
const HeroSection = () => {
    const stats = [
        { icon: Users, value: "10,000+", label: "Active Donors" },
        { icon: Building2, value: "500+", label: "Partner Hospitals" },
        { icon: Clock, value: "< 30min", label: "Avg Response Time" },
    ];
    return (_jsxs("section", { id: "home", className: "relative hero-gradient overflow-hidden", children: [_jsxs("div", { className: "absolute inset-0 opacity-5", children: [_jsx("div", { className: "absolute top-20 left-10 w-64 h-64 rounded-full bg-primary blur-3xl" }), _jsx("div", { className: "absolute bottom-20 right-10 w-96 h-96 rounded-full bg-primary blur-3xl" })] }), _jsx("div", { className: "container relative py-20 lg:py-32", children: _jsxs("div", { className: "max-w-3xl mx-auto text-center animate-fade-in-up", children: [_jsxs("div", { className: "inline-flex items-center gap-2 px-4 py-2 rounded-full bg-secondary text-secondary-foreground mb-6", children: [_jsx(Heart, { className: "h-4 w-4", fill: "currentColor" }), _jsx("span", { className: "text-sm font-medium", children: "Save Lives, Donate Blood" })] }), _jsxs("h1", { className: "text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-6", children: ["Connecting ", _jsx("span", { className: "text-gradient", children: "Blood Donors" }), " with", " ", _jsx("span", { className: "text-gradient", children: "Hospitals" }), " in Need"] }), _jsx("p", { className: "text-lg md:text-xl text-muted-foreground mb-8 max-w-2xl mx-auto", children: "RedDrop is your centralized platform for blood donation. Register as a donor, find nearby hospitals, and help save lives during emergencies." }), _jsxs("div", { className: "flex flex-col sm:flex-row items-center justify-center gap-4 mb-16", children: [_jsx(Button, { variant: "hero", size: "xl", asChild: true, children: _jsxs(Link, { to: "/?tab=donor#register", children: [_jsx(Heart, { className: "h-5 w-5" }), "Register as Emergency Donor"] }) }), _jsx(Button, { variant: "outline", size: "xl", asChild: true, children: _jsxs(Link, { to: "/?tab=hospital#register", children: [_jsx(Building2, { className: "h-5 w-5" }), "Request for Blood"] }) })] }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-3 gap-8", children: stats.map((stat, index) => (_jsxs("div", { className: "flex flex-col items-center p-6 rounded-2xl bg-card card-shadow transition-all duration-300 hover:card-shadow-hover", style: { animationDelay: `${index * 100}ms` }, children: [_jsx(stat.icon, { className: "h-8 w-8 text-primary mb-3" }), _jsx("span", { className: "text-3xl font-bold text-foreground", children: stat.value }), _jsx("span", { className: "text-sm text-muted-foreground", children: stat.label })] }, stat.label))) })] }) })] }));
};
export default HeroSection;
