import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MapPin, Phone, AlertTriangle, Building2 } from "lucide-react";
import { Button } from "./ui/button";
import { cn } from "@/lib/utils";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger, } from "./ui/dialog";
const HospitalCard = ({ name, location, distance, requirements, phone, email, }) => {
    const hasUrgent = requirements.some((r) => r.isUrgent);
    return (_jsxs("div", { className: cn("group bg-card rounded-2xl card-shadow transition-all duration-300 hover:card-shadow-hover hover:-translate-y-1", hasUrgent ? "p-5" : "p-6", hasUrgent && "ring-2 ring-urgent/50"), children: [hasUrgent && (_jsxs("div", { className: "flex items-center gap-1.5 text-urgent mb-3", children: [_jsx(AlertTriangle, { className: "h-3.5 w-3.5" }), _jsx("span", { className: "text-xs font-semibold", children: "Urgent Requirement" })] })), _jsxs("div", { className: "mb-4", children: [_jsx("h3", { className: "font-semibold text-lg text-foreground mb-2", children: name }), _jsx("div", { className: "space-y-1.5 text-sm text-muted-foreground", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(MapPin, { className: "h-4 w-4 flex-shrink-0" }), _jsx("span", { className: "truncate", children: location }), _jsxs("span", { className: "text-primary font-medium", children: ["(", distance, ")"] })] }) })] }), _jsxs("div", { className: "mb-4", children: [_jsx("p", { className: "text-sm font-medium text-foreground mb-3", children: "Blood Required:" }), requirements.length > 0 ? (_jsx("div", { className: "flex flex-wrap gap-2", children: requirements.map((req, index) => (_jsxs("div", { className: cn("flex items-center gap-2 rounded-full", req.isUrgent
                                ? "bg-urgent/10 text-urgent font-medium px-2.5 py-1 text-xs"
                                : "bg-secondary text-secondary-foreground px-3 py-1.5 text-sm"), children: [_jsx("span", { className: "font-bold", children: req.bloodGroup }), _jsxs("span", { className: "text-xs", children: ["(", req.units, " units)"] })] }, index))) })) : (_jsx("p", { className: "text-sm text-muted-foreground", children: "No active blood requirements." }))] }), _jsxs("div", { className: "pt-4 border-t flex items-center gap-3", children: [_jsx(Button, { variant: hasUrgent ? "urgent" : "default", size: "sm", className: "flex-1", asChild: true, disabled: !phone, children: _jsxs("a", { href: phone ? `tel:${phone}` : "#", "aria-disabled": !phone, children: [_jsx(Phone, { className: "h-4 w-4" }), "Respond Now"] }) }), _jsxs(Dialog, { children: [_jsx(DialogTrigger, { asChild: true, children: _jsx(Button, { variant: "outline", size: "sm", className: "flex-1", children: "View Details" }) }), _jsxs(DialogContent, { children: [_jsxs(DialogHeader, { children: [_jsxs(DialogTitle, { className: "flex items-center gap-2", children: [_jsx(Building2, { className: "h-4 w-4" }), name] }), _jsx(DialogDescription, { children: "Hospital details and current blood requirements." })] }), _jsxs("div", { className: "space-y-3 text-sm", children: [_jsxs("p", { children: [_jsx("span", { className: "font-medium", children: "Location:" }), " ", location] }), _jsxs("p", { children: [_jsx("span", { className: "font-medium", children: "Distance (from your location, approx.):" }), " ", distance] }), _jsxs("p", { children: [_jsx("span", { className: "font-medium", children: "Phone:" }), " ", phone || "Not shared"] }), _jsxs("p", { children: [_jsx("span", { className: "font-medium", children: "Email:" }), " ", email || "Not shared"] }), _jsxs("div", { children: [_jsx("p", { className: "font-medium mb-2", children: "Blood Requirements:" }), requirements.length > 0 ? (_jsx("ul", { className: "space-y-1", children: requirements.map((req, index) => (_jsxs("li", { children: [req.bloodGroup, " - ", req.units, " units ", req.isUrgent ? "(Urgent)" : ""] }, `${req.bloodGroup}-${index}`))) })) : (_jsx("p", { className: "text-muted-foreground", children: "No active blood requirements." }))] })] })] })] })] })] }));
};
export default HospitalCard;
